# Generated by Django 2.0 on 2017-12-09 11:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Index',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Leg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_weight', models.IntegerField()),
                ('time', models.IntegerField()),
                ('cost', models.IntegerField()),
                ('leg_type', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient', models.IntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.IntegerField()),
                ('cost', models.IntegerField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='implementation.Order')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.IntegerField()),
                ('legs', models.ManyToManyField(through='implementation.Index', to='implementation.Leg')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='implementation.Order')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Vertex',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postcodes', models.TextField()),
                ('adress', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='order',
            name='deliver_from',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='implementation.Vertex'),
        ),
        migrations.AddField(
            model_name='order',
            name='deliver_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='implementation.Vertex'),
        ),
        migrations.AddField(
            model_name='order',
            name='follows',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='implementation.Route'),
        ),
        migrations.AddField(
            model_name='leg',
            name='from_vertex',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='implementation.Vertex'),
        ),
        migrations.AddField(
            model_name='leg',
            name='to_vertex',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='implementation.Vertex'),
        ),
        migrations.AddField(
            model_name='index',
            name='leg',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='implementation.Leg'),
        ),
        migrations.AddField(
            model_name='index',
            name='route',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='implementation.Route'),
        ),
    ]
